FROM postgres

USER postgres
WORKDIR /app

COPY src/sql/createTable.sql /docker-entrypoint-initdb.d/1_createTable.sql
COPY src/sql/insertTable.sql /docker-entrypoint-initdb.d/2_insertTable.sql

COPY --chown=postgres:postgres ./tests/scripts/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

EXPOSE 5432