START TRANSACTION;

DO $$
    BEGIN
    DROP TABLE IF EXISTS REGISTRATION_INVITES;
    DROP TABLE IF EXISTS USERS CASCADE;
    DROP TABLE IF EXISTS TOKENS CASCADE;
    DROP TABLE IF EXISTS CHANNELS CASCADE;
    DROP TABLE IF EXISTS MESSAGES CASCADE;
    DROP TABLE IF EXISTS PARTICIPANTS CASCADE;

    CREATE TABLE REGISTRATION_INVITES(
        code VARCHAR(255) PRIMARY KEY
    );

    CREATE TABLE IF NOT EXISTS USERS(
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL,
        password_validation VARCHAR(255) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS TOKENS(
        token VARCHAR(255) PRIMARY KEY,
        createdAt TIMESTAMP NOT NULL,
        lastUsedAt TIMESTAMP NOT NULL,
        user_id INTEGER NOT NULL,
        FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS CHANNELS(
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        owner_id INTEGER NOT NULL,
        type VARCHAR(255) NOT NULL CHECK (type IN ('PUBLIC', 'PRIVATE')),
        invite_code_with_write VARCHAR(255),
        invite_code_read_only VARCHAR(255),

        FOREIGN KEY (owner_id) REFERENCES USERS(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS PARTICIPANTS(
        id SERIAL PRIMARY KEY,
        user_id INTEGER NOT NULL,
        channel_id INTEGER NOT NULL,
        type VARCHAR(255) NOT NULL CHECK (type IN ('OWNER', 'WRITER', 'READER_ONLY')),
        FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
        FOREIGN KEY (channel_id) REFERENCES CHANNELS(id) ON DELETE CASCADE,
        CONSTRAINT unique_participant UNIQUE (user_id, channel_id)
    );

    CREATE TABLE IF NOT EXISTS MESSAGES(
        id SERIAL PRIMARY KEY,
        text VARCHAR(255) NOT NULL,
        author_id INTEGER NOT NULL,
        time TIMESTAMP NOT NULL,
        FOREIGN KEY (author_id) REFERENCES PARTICIPANTS(id) ON DELETE CASCADE
    );
    END;
$$ LANGUAGE "plpgsql";
COMMIT;

-- ROLLBACK;